### PR TITLE
[WT-44]:chore/improve-lock-endpoint-statuses

### PR DESCRIPTION
**Pull request by JoanVicens**

### CODE REVIEW

**Review by sg-gs — APPROVED** [review]

**Comment by sg-gs** [comment]
LGTM. Merge when you need it.

**Comment by fabioespinosa** [comment]
@JoanVicens should we get it merged now?

**Comment by JoanVicens** [comment]
hmmm, I would prefer to wait until Monday. The change was to help diagnose a problem with desktop sync, but we discovered that the problem was on the Redis machine. So it's not a priority in any sense

**Comment by fabioespinosa** [comment]
Sounds reasonable 👌

**Pull request merged**
